api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
# Copyright © 2020 Caroline Canebier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""Defines the URLs of the API

A custom router is used to register all the routes. That allows to register
all the URL patterns from the viewsets as a standard router but, the views
can also be register. That way a complete API root page presenting all URLs
can be generated automatically.
"""

from django.conf.urls import url, include
from importlib import import_module

from . import views
from .routers import AllViewsRouter
from django.conf import settings

router = AllViewsRouter()

urls_viewset = []
urls_view = []
urls_functional_view = []

for app in settings.INSTALLED_APPS:
    try:
        module = import_module(".api.urls", package=app)
        urls_viewset += getattr(module, "urls_viewset", [])
        urls_view += getattr(module, "urls_view", [])
        urls_functional_view += getattr(module, "urls_functional_view", [])
    except ImportError:
        continue

for _url, viewset, name in urls_viewset:
    if name == None:
        router.register_viewset(_url, viewset)
    else:
        router.register_viewset(_url, viewset, basename=name)

for _url, view in urls_view:
    router.register_view(_url, view)

for _url, view, name in urls_functional_view:
    router.register_functional_view(_url, view, name)

# TOKEN AUTHENTICATION
router.register_view(r"token-auth", views.ObtainExpiringAuthToken)

urlpatterns = [url(r"^", include(router.urls))]

re2o/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""re2o URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home)
    3. Optional: Add a custom name for this URL:
         url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view())
    3. Optional: Add a custom name for this URL:
         url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
    2. Optional: Add a custom namespace for all URL using this urlpatterns:
         url(r'^blog/', include('blog.urls'), namespace='blog')
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from .settings_local import OPTIONNAL_APPS_RE2O

from .views import index, about_page, contact_page

# Admin site configuration
admin.site.index_title = _("Homepage")
admin.site.index_template = "admin/custom_index.html"

handler500 = "re2o.views.handler500"
handler404 = "re2o.views.handler404"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^about/$", about_page, name="about"),
    url(r"^contact/$", contact_page, name="contact"),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^search/", include("search.urls", namespace="search")),
    url(r"^cotisations/", include("cotisations.urls", namespace="cotisations")),
    url(r"^machines/", include("machines.urls", namespace="machines")),
    url(r"^topologie/", include("topologie.urls", namespace="topologie")),
    url(r"^logs/", include("logs.urls", namespace="logs")),
    url(r"^preferences/", include("preferences.urls", namespace="preferences")),
    # Include contrib auth and contrib admin
    # manage/login/ is redirected to the non-admin login page
    url(r"^", include("django.contrib.auth.urls")),
    url(r"^admin/login/$", RedirectView.as_view(pattern_name="login")),
    url(r"^admin/", include(admin.site.urls)),
]


urlpatterns += [
    url(r"^{}/".format(app), include("{}.urls".format(app), namespace=app))
    for app in OPTIONNAL_APPS_RE2O
]

# Add debug_toolbar URLs if activated
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]
if "api" in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^api/", include("api.urls", namespace="api"))]

topologie/api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from . import views

urls_viewset = [
    (r"topologie/stack", views.StackViewSet, None),
    (r"topologie/acesspoint", views.AccessPointViewSet, None),
    (r"topologie/switch", views.SwitchViewSet, None),
    (r"topologie/server", views.ServerViewSet, None),
    (r"topologie/modelswitch", views.ModelSwitchViewSet, None),
    (r"topologie/constructorswitch", views.ConstructorSwitchViewSet, None),
    (r"topologie/switchbay", views.SwitchBayViewSet, None),
    (r"topologie/building", views.BuildingViewSet, None),
    (r"topologie/dormitory", views.DormitoryViewSet, None),
    (r"topologie/switchport", views.SwitchPortViewSet, "switchport"),
    (r"topologie/portprofile", views.PortProfileViewSet, "portprofile"),
    (r"topologie/room", views.RoomViewSet, None)
]

urls_view = [
    (r"topologie/switchs-ports-config", views.SwitchPortView),
    (r"topologie/switchs-role", views.RoleView),

    # Deprecated
    (r"switchs/ports-config", views.SwitchPortView),
    (r"switchs/role", views.RoleView),
]

topologie/urls.py
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""topologie.urls
The defined URLs for topologie app. Included in re2o.urls.
"""

from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from . import views_autocomplete

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^index_ap/$", views.index_ap, name="index-ap"),
    url(r"^new_ap/$", views.new_ap, name="new-ap"),
    url(r"^edit_ap/(?P<accesspointid>[0-9]+)$", views.edit_ap, name="edit-ap"),
    url(
        r"^create_ports/(?P<switchid>[0-9]+)$", views.create_ports, name="create-ports"
    ),
    url(r"^index_room/$", views.index_room, name="index-room"),
    url(r"^new_room/$", views.new_room, name="new-room"),
    url(r"^edit_room/(?P<roomid>[0-9]+)$", views.edit_room, name="edit-room"),
    url(r"^del_room/(?P<roomid>[0-9]+)$", views.del_room, name="del-room"),
    url(r"^new_switch/$", views.new_switch, name="new-switch"),
    url(r"^switch/(?P<switchid>[0-9]+)$", views.index_port, name="index-port"),
    url(r"^edit_port/(?P<portid>[0-9]+)$", views.edit_port, name="edit-port"),
    url(r"^new_port/(?P<switchid>[0-9]+)$", views.new_port, name="new-port"),
    url(r"^del_port/(?P<portid>[0-9]+)$", views.del_port, name="del-port"),
    url(r"^edit_switch/(?P<switchid>[0-9]+)$", views.edit_switch, name="edit-switch"),
    url(r"^new_stack/$", views.new_stack, name="new-stack"),
    url(
        r"^index_stack/$",
        views.index_stack,
        name="index-stack",
    ),
    url(
        r"^index_switch_bay/$",
        views.index_switch_bay,
        name="index-switch-bay",
    ),
    url(
        r"^index_building/$",
        views.index_building,
        name="index-building",
    ),
    url(
        r"^index_dormitory/$",
        views.index_dormitory,
        name="index-dormitory",
    ),
    url(r"^edit_stack/(?P<stackid>[0-9]+)$", views.edit_stack, name="edit-stack"),
    url(r"^del_stack/(?P<stackid>[0-9]+)$", views.del_stack, name="del-stack"),
    url(r"^index_model_switch/$", views.index_model_switch, name="index-model-switch"),
    url(r"^index_model_switch/$", views.index_model_switch, name="index-model-switch"),
    url(r"^new_model_switch/$", views.new_model_switch, name="new-model-switch"),
    url(
        r"^edit_model_switch/(?P<modelswitchid>[0-9]+)$",
        views.edit_model_switch,
        name="edit-model-switch",
    ),
    url(
        r"^del_model_switch/(?P<modelswitchid>[0-9]+)$",
        views.del_model_switch,
        name="del-model-switch",
    ),
    url(
        r"^new_constructor_switch/$",
        views.new_constructor_switch,
        name="new-constructor-switch",
    ),
    url(
        r"^edit_constructor_switch/(?P<constructorswitchid>[0-9]+)$",
        views.edit_constructor_switch,
        name="edit-constructor-switch",
    ),
    url(
        r"^del_constructor_switch/(?P<constructorswitchid>[0-9]+)$",
        views.del_constructor_switch,
        name="del-constructor-switch",
    ),
    url(r"^new_switch_bay/$", views.new_switch_bay, name="new-switch-bay"),
    url(
        r"^edit_switch_bay/(?P<switchbayid>[0-9]+)$",
        views.edit_switch_bay,
        name="edit-switch-bay",
    ),
    url(
        r"^del_switch_bay/(?P<switchbayid>[0-9]+)$",
        views.del_switch_bay,
        name="del-switch-bay",
    ),
    url(r"^new_building/$", views.new_building, name="new-building"),
    url(
        r"^edit_building/(?P<buildingid>[0-9]+)$",
        views.edit_building,
        name="edit-building",
    ),
    url(
        r"^del_building/(?P<buildingid>[0-9]+)$",
        views.del_building,
        name="del-building",
    ),
    url(r"^new_dormitory/$", views.new_dormitory, name="new-dormitory"),
    url(
        r"^edit_dormitory/(?P<dormitoryid>[0-9]+)$",
        views.edit_dormitory,
        name="edit-dormitory",
    ),
    url(
        r"^del_dormitory/(?P<dormitoryid>[0-9]+)$",
        views.del_dormitory,
        name="del-dormitory",
    ),
    url(r"^index_port_profile/$", views.index_port_profile, name="index-port-profile"),
    url(r"^new_port_profile/$", views.new_port_profile, name="new-port-profile"),
    url(
        r"^edit_port_profile/(?P<portprofileid>[0-9]+)$",
        views.edit_port_profile,
        name="edit-port-profile",
    ),
    url(
        r"^del_port_profile/(?P<portprofileid>[0-9]+)$",
        views.del_port_profile,
        name="del-port-profile",
    ),
    url(
        r"^edit_vlanoptions/(?P<vlanid>[0-9]+)$",
        views.edit_vlanoptions,
        name="edit-vlanoptions",
    ),
    url(r"^add_module/$", views.add_module, name="add-module"),
    url(
        r"^edit_module/(?P<moduleswitchid>[0-9]+)$",
        views.edit_module,
        name="edit-module",
    ),
    url(
        r"^del_module/(?P<moduleswitchid>[0-9]+)$", views.del_module, name="del-module"
    ),
    url(r"^index_module/$", views.index_module, name="index-module"),
    url(r"^add_module_on/$", views.add_module_on, name="add-module-on"),
    url(
        r"^edit_module_on/(?P<moduleonswitchid>[0-9]+)$",
        views.edit_module_on,
        name="edit-module-on",
    ),
    url(
        r"^del_module_on/(?P<moduleonswitchid>[0-9]+)$",
        views.del_module_on,
        name="del-module-on",
    ),
    ### Autocomplete Views
    url(r'^room-autocomplete/$', views_autocomplete.RoomAutocomplete.as_view(), name='room-autocomplete',),
    url(r'^building-autocomplete/$', views_autocomplete.BuildingAutocomplete.as_view(), name='building-autocomplete',),
    url(r'^dormitory-autocomplete/$', views_autocomplete.DormitoryAutocomplete.as_view(), name='dormitory-autocomplete',),
    url(r'^switch-autocomplete/$', views_autocomplete.SwitchAutocomplete.as_view(), name='switch-autocomplete',),
    url(r'^port-autocomplete/$', views_autocomplete.PortAutocomplete.as_view(), name='profile-autocomplete',),
    url(r'^portprofile-autocomplete/$', views_autocomplete.PortProfileAutocomplete.as_view(), name='portprofile-autocomplete',),
    url(r'^switchbay-autocomplete/$', views_autocomplete.SwitchBayAutocomplete.as_view(), name='switchbay-autocomplete',),
]

topologie/templates/topologie/aff_model_switch.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load acl %}
{% load logs_extra %}
{% load i18n %}

{% if model_switch_list.paginator %}
    {% include 'pagination.html' with list=model_switch_list %}
{% endif %}

<table class="table table-striped">
    <thead>
        <tr>
            {% trans "Reference" as tr_ref %}
            <th>{% include 'buttons/sort.html' with prefix='model-switch' col='reference' text=tr_ref %}</th>
            <th>{% trans "Commercial name" %}</th>
	    <th>{% trans "Firmware" %}</th>
            {% trans "Switch constructor" as tr_constructor %}
            <th>{% include 'buttons/sort.html' with prefix='model-switch' col='constructor' text=tr_constructor %}</th>
	    <th>{% trans "Switches" %}
	    <th></th>
        </tr>
    </thead>
    {% for model_switch in model_switch_list %}
    <tr>
        <td>{{ model_switch.reference }}</td>
        <td>{{ model_switch.commercial_name }}</td>
        <td>{{ model_switch.firmware }}</td>
        <td>{{ model_switch.constructor }}</td>
	<td>
	    {% for switch in model_switch.switch_set.all %}
	    <a href="{% url 'topologie:index-port' switch.pk %}">
		{{ switch }}
	    </a>
	    {% endfor %}
	</td>
        <td class="text-right">
            {% can_edit model_switch %}
            {% include 'buttons/edit.html' with href='topologie:edit-model-switch' id=model_switch.id %}
            {% acl_end %}
            {% history_button model_switch %}
            {% can_delete model_switch %}
            {% include 'buttons/suppr.html' with href='topologie:del-model-switch' id=model_switch.id %}
            {% acl_end %}
        </td>
    </tr>
    {% endfor %}
</table>

{% if model_switch_list.paginator %}
    {% include 'pagination.html' with list=model_switch_list %}
{% endif %}

topologie/templates/topologie/aff_port.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load acl %}
{% load logs_extra %}
{% load i18n %}

<div class="table-responsive">
    <table class="table table-striped">
        <thead>
            <tr>
                {% trans "Port" as tr_port %}
                <th>{% include 'buttons/sort.html' with prefix='port' col='port' text=tr_port %}</th>
                {%  if search %}
                    <th>{% trans "Switch" %}</th>
                {% endif %}
                {% trans "Room" as tr_room %}
                <th>{% include 'buttons/sort.html' with prefix='port' col='room' text=tr_room %}</th>
                {% trans "Interface" as tr_interface %}
                <th>{% include 'buttons/sort.html' with prefix='port' col='interface' text=tr_interface %}</th>
                {% trans "Related port" as tr_related_port %}
                <th>{% include 'buttons/sort.html' with prefix='port' col='related' text=tr_related_port %}</th>
                <th>{% trans "Port state" %}</th>
                <th>{% trans "Port profile" %}</th>
                <th>{% trans "Details" %}</th>
                <th></th>
            </tr>
        </thead>
       {% for port in port_list %}
            <tr>
			<td>{{ port.port }}</td>
            {% if search %}
                <td>
                    <a href="{% url 'topologie:index-port' switchid=port.switch.id %}">{{ port.switch }}</a>
                </td>
            {% endif %}
                <td>
                    {% if port.room %}
                    {{ port.room }}
                    {% endif %}
                </td>
                <td>
                    {% if port.machine_interface %}
                    {% can_view port.machine_interface.machine.user %}
                    <a href="{% url 'users:profil' userid=port.machine_interface.machine.user.id %}">
                        {{ port.machine_interface }}
                    </a>
                    {% acl_end %}
                    {% endif %}
                </td>
                <td>
                    {% if port.related %}
                    {% can_view port.related.switch %}
                    <a href="{% url 'topologie:index-port' switchid=port.related.switch.id %}">
                        {{ port.related }}
                    </a>
                    {% acl_else %}
                    {{ port.related }}
                    {% acl_end %}
                    {% endif %}
                </td>
		<td>
                    {% if port.state %}
                    <i class="text-success">{% trans "Active" %}</i>
                    {% else %}
                    <i class="text-danger">{% trans "Disabled" %}</i>
                    {% endif %}
                </td>
                <td>
                    {% if not port.custom_profile %}
                    <u>{% trans "Default: " %}</u>
                    {% endif %}
                    {{ port.get_port_profile }}
                </td>
                <td>{{ port.details }}</td>
                <td class="text-right">
                    {% can_edit port %}
                    {% include 'buttons/edit.html' with href='topologie:edit-port' id=port.id %}
                    {% acl_end %}
                    {% history_button port %}
                    {% can_delete port %}
                    {% include 'buttons/suppr.html' with href='topologie:del-port' id=port.id %}
                    {% acl_end %}
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

topologie/templates/topologie/aff_stacks.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load acl %}
{% load logs_extra %}
{% load i18n %}

<table class="table table-striped">
    <thead>
        <tr>
            {% trans "Stack" as tr_stack %}
            <th>{% include 'buttons/sort.html' with prefix='stack' col='name' text=tr_stack %}</th>
            {% trans "ID" as tr_id %}
            <th>{% include 'buttons/sort.html' with prefix='stack' col='id' text=id %}</th>
            <th>{% trans "Details" %}</th>
            <th>{% trans "Members" %}</th>
            <th></th>
        </tr>
    </thead>
    {% for stack in stack_list %}
        <tr>
            <td>{{ stack.name }}</td>
            <td>{{ stack.stack_id }}</td>
            <td>{{ stack.details }}</td>
            <td>
            {% for switch in stack.switch_set.all %}
                <a href="{% url 'topologie:index-port' switch.id %}">
                    {{ switch }}
                </a>
            {% endfor %}
            </td>
            <td class="text-right">
                {% can_edit stack %}
                {% include 'buttons/edit.html' with href='topologie:edit-stack' id=stack.id %}
                {% acl_end %}
                {% history_button stack %}
                {% can_delete stack %}
                {% include 'buttons/suppr.html' with href='topologie:del-stack' id=stack.id %}
                {% acl_end %}
            </td>
        </tr>
    {% endfor %}
</table>

topologie/templates/topologie/index_p.html
{% extends 'topologie/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load acl %}
{% load i18n %}

{% block title %}{% trans "Topology" %}{% endblock %}

{% block content %}
<h2>{% trans "Switch:"%} {{ switch }}</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>{% trans "Switch bay" %}</th>
            <th>{% trans "Switch model" %}</th>
            <th>{% trans "Stack" %}</th>
        </tr>
    </thead>
    <tr>
        <td>{{ switch.switchbay }}</td>
        <td>{{ switch.model }}</td>
        <td>{{ switch.stack }}</td>
    </tr>
</table>
<hr>
{% include 'buttons/edit.html' with href='topologie:edit-switch' id=id_switch %}
{% can_create Port %}
<a class="btn btn-primary btn-sm" role="button" href="{% url 'topologie:new-port' id_switch %}"><i class="fa fa-plus"></i> {% trans "Add a port" %}</a>
<a class="btn btn-primary btn-sm" role="button" href="{% url 'topologie:create-ports' id_switch %}"><i class="fa fa-plus"></i> {% trans "Add ports to the port list" %}</a>
{% acl_end %}
<hr>
{% include 'topologie/aff_repr_switch.html' with port_list=port_list %}
{% include 'topologie/aff_port.html' with port_list=port_list %}
    <br />
    <br />
    <br />
{% endblock %}

topologie/templates/topologie/sidebar.html
{% extends 'base.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}


{% block sidebar %}
{% endblock %}