api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
# Copyright © 2020 Caroline Canebier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""Defines the URLs of the API

A custom router is used to register all the routes. That allows to register
all the URL patterns from the viewsets as a standard router but, the views
can also be register. That way a complete API root page presenting all URLs
can be generated automatically.
"""

from django.conf.urls import url, include
from importlib import import_module

from . import views
from .routers import AllViewsRouter
from django.conf import settings

router = AllViewsRouter()

urls_viewset = []
urls_view = []
urls_functional_view = []

for app in settings.INSTALLED_APPS:
    try:
        module = import_module(".api.urls", package=app)
        urls_viewset += getattr(module, "urls_viewset", [])
        urls_view += getattr(module, "urls_view", [])
        urls_functional_view += getattr(module, "urls_functional_view", [])
    except ImportError:
        continue

for _url, viewset, name in urls_viewset:
    if name == None:
        router.register_viewset(_url, viewset)
    else:
        router.register_viewset(_url, viewset, basename=name)

for _url, view in urls_view:
    router.register_view(_url, view)

for _url, view, name in urls_functional_view:
    router.register_functional_view(_url, view, name)

# TOKEN AUTHENTICATION
router.register_view(r"token-auth", views.ObtainExpiringAuthToken)

urlpatterns = [url(r"^", include(router.urls))]

cotisations/api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from . import views

urls_viewset = [
    (r"cotisations/facture", views.FactureViewSet, None),
    (r"cotisations/vente", views.VenteViewSet, None),
    (r"cotisations/article", views.ArticleViewSet, None),
    (r"cotisations/banque", views.BanqueViewSet, None),
    (r"cotisations/paiement", views.PaiementViewSet, None),
    (r"cotisations/cotisation", views.CotisationViewSet, None)
]

urls_view = [
    (r"cotisations/reminder-get-users", views.ReminderView),

    # Deprecated
    (r"reminder/get-users", views.ReminderView),
]

cotisations/urls.py
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""cotisations.urls
The defined URLs for the Cotisations app
"""

from __future__ import unicode_literals

from django.conf.urls import url

from . import views, views_autocomplete
from . import payment_methods

urlpatterns = [
    url(r"^new_facture/(?P<userid>[0-9]+)$", views.new_facture, name="new-facture"),
    url(
        r"^edit_facture/(?P<factureid>[0-9]+)$", views.edit_facture, name="edit-facture"
    ),
    url(r"^del_facture/(?P<factureid>[0-9]+)$", views.del_facture, name="del-facture"),
    url(r"^facture_pdf/(?P<factureid>[0-9]+)$", views.facture_pdf, name="facture-pdf"),
    url(r"^voucher_pdf/(?P<factureid>[0-9]+)$", views.voucher_pdf, name="voucher-pdf"),
    url(r"^new_cost_estimate/$", views.new_cost_estimate, name="new-cost-estimate"),
    url(
        r"^index_cost_estimate/$", views.index_cost_estimate, name="index-cost-estimate"
    ),
    url(
        r"^cost_estimate_pdf/(?P<costestimateid>[0-9]+)$",
        views.cost_estimate_pdf,
        name="cost-estimate-pdf",
    ),
    url(
        r"^index_custom_invoice/$",
        views.index_custom_invoice,
        name="index-custom-invoice",
    ),
    url(
        r"^edit_cost_estimate/(?P<costestimateid>[0-9]+)$",
        views.edit_cost_estimate,
        name="edit-cost-estimate",
    ),
    url(
        r"^cost_estimate_to_invoice/(?P<costestimateid>[0-9]+)$",
        views.cost_estimate_to_invoice,
        name="cost-estimate-to-invoice",
    ),
    url(
        r"^del_cost_estimate/(?P<costestimateid>[0-9]+)$",
        views.del_cost_estimate,
        name="del-cost-estimate",
    ),
    url(r"^new_custom_invoice/$", views.new_custom_invoice, name="new-custom-invoice"),
    url(
        r"^edit_custom_invoice/(?P<custominvoiceid>[0-9]+)$",
        views.edit_custom_invoice,
        name="edit-custom-invoice",
    ),
    url(
        r"^custom_invoice_pdf/(?P<custominvoiceid>[0-9]+)$",
        views.custom_invoice_pdf,
        name="custom-invoice-pdf",
    ),
    url(
        r"^del_custom_invoice/(?P<custominvoiceid>[0-9]+)$",
        views.del_custom_invoice,
        name="del-custom-invoice",
    ),
    url(r"^credit_solde/(?P<userid>[0-9]+)$", views.credit_solde, name="credit-solde"),
    url(r"^add_article/$", views.add_article, name="add-article"),
    url(
        r"^edit_article/(?P<articleid>[0-9]+)$", views.edit_article, name="edit-article"
    ),
    url(r"^del_article/$", views.del_article, name="del-article"),
    url(r"^add_paiement/$", views.add_paiement, name="add-paiement"),
    url(
        r"^edit_paiement/(?P<paiementid>[0-9]+)$",
        views.edit_paiement,
        name="edit-paiement",
    ),
    url(r"^del_paiement/$", views.del_paiement, name="del-paiement"),
    url(r"^add_banque/$", views.add_banque, name="add-banque"),
    url(r"^edit_banque/(?P<banqueid>[0-9]+)$", views.edit_banque, name="edit-banque"),
    url(r"^del_banque/$", views.del_banque, name="del-banque"),
    url(r"^index_article/$", views.index_article, name="index-article"),
    url(r"^index_banque/$", views.index_banque, name="index-banque"),
    url(r"^index_paiement/$", views.index_paiement, name="index-paiement"),
    url(r"^control/$", views.control, name="control"),
    url(r"^$", views.index, name="index"),
    ### Autocomplete Views
    url(r'^banque-autocomplete/$', views_autocomplete.BanqueAutocomplete.as_view(), name='banque-autocomplete',),
] + payment_methods.urls.urlpatterns

re2o/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""re2o URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home)
    3. Optional: Add a custom name for this URL:
         url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view())
    3. Optional: Add a custom name for this URL:
         url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
    2. Optional: Add a custom namespace for all URL using this urlpatterns:
         url(r'^blog/', include('blog.urls'), namespace='blog')
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from .settings_local import OPTIONNAL_APPS_RE2O

from .views import index, about_page, contact_page

# Admin site configuration
admin.site.index_title = _("Homepage")
admin.site.index_template = "admin/custom_index.html"

handler500 = "re2o.views.handler500"
handler404 = "re2o.views.handler404"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^about/$", about_page, name="about"),
    url(r"^contact/$", contact_page, name="contact"),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^search/", include("search.urls", namespace="search")),
    url(r"^cotisations/", include("cotisations.urls", namespace="cotisations")),
    url(r"^machines/", include("machines.urls", namespace="machines")),
    url(r"^topologie/", include("topologie.urls", namespace="topologie")),
    url(r"^logs/", include("logs.urls", namespace="logs")),
    url(r"^preferences/", include("preferences.urls", namespace="preferences")),
    # Include contrib auth and contrib admin
    # manage/login/ is redirected to the non-admin login page
    url(r"^", include("django.contrib.auth.urls")),
    url(r"^admin/login/$", RedirectView.as_view(pattern_name="login")),
    url(r"^admin/", include(admin.site.urls)),
]


urlpatterns += [
    url(r"^{}/".format(app), include("{}.urls".format(app), namespace=app))
    for app in OPTIONNAL_APPS_RE2O
]

# Add debug_toolbar URLs if activated
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]
if "api" in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^api/", include("api.urls", namespace="api"))]

cotisations/api/views.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from rest_framework import viewsets, generics

from . import serializers
import cotisations.models as cotisations
import preferences.models as preferences

class FactureViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Facture` objects.
    """

    queryset = cotisations.Facture.objects.all()
    serializer_class = serializers.FactureSerializer


class FactureViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Facture` objects.
    """

    queryset = cotisations.BaseInvoice.objects.all()
    serializer_class = serializers.BaseInvoiceSerializer


class VenteViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Vente` objects.
    """

    queryset = cotisations.Vente.objects.all()
    serializer_class = serializers.VenteSerializer


class ArticleViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Article` objects.
    """

    queryset = cotisations.Article.objects.all()
    serializer_class = serializers.ArticleSerializer


class BanqueViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Banque` objects.
    """

    queryset = cotisations.Banque.objects.all()
    serializer_class = serializers.BanqueSerializer


class PaiementViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Paiement` objects.
    """

    queryset = cotisations.Paiement.objects.all()
    serializer_class = serializers.PaiementSerializer


class CotisationViewSet(viewsets.ReadOnlyModelViewSet):
    """Exposes list and details of `cotisations.models.Cotisation` objects.
    """

    queryset = cotisations.Cotisation.objects.all()
    serializer_class = serializers.CotisationSerializer


class ReminderView(generics.ListAPIView):
    """Output for users to remind an end of their subscription.
    """

    queryset = preferences.Reminder.objects.all()
    serializer_class = serializers.ReminderSerializer

cotisations/payment_methods/cheque/views.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018  Hugo Levy-Falk
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""Payment

Here are defined some views dedicated to cheque payement.
"""

from django.urls import reverse
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils.translation import ugettext as _

from cotisations.models import Facture as Invoice
from cotisations.utils import find_payment_method

from .models import ChequePayment
from .forms import InvoiceForm


@login_required
def cheque(request, invoice_pk):
    """This view validate an invoice with the data from a cheque."""
    invoice = get_object_or_404(Invoice, pk=invoice_pk)
    payment_method = find_payment_method(invoice.paiement)
    if invoice.valid or not isinstance(payment_method, ChequePayment):
        messages.error(request, _("You can't pay this invoice with a cheque."))
        return redirect(reverse("users:profil", kwargs={"userid": request.user.pk}))
    form = InvoiceForm(request.POST or None, instance=invoice)
    if form.is_valid():
        form.instance.valid = True
        # For is saved in call to end_payment
        return form.instance.paiement.end_payment(
            form.instance, request, use_payment_method=False
        )
    return render(
        request,
        "cotisations/payment.html",
        {"form": form, "amount": invoice.prix_total()},
    )

cotisations/templates/cotisations/aff_cotisations.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load acl %}
{% load i18n %}
{% load logs_extra %}

<div class="table-responsive">
{% if facture_list.paginator %}
    {% include 'pagination.html' with list=facture_list %}
{% endif %}

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    {% trans "User" as tr_user %}
                    {% include 'buttons/sort.html' with prefix='cotis' col='user' text=tr_user %}
                </th>
                <th>{% trans "Designation" %}</th>
                <th>{% trans "Total price" %}</th>
                <th>
                    {% trans "Payment method" as tr_payment_method %}
                    {% include 'buttons/sort.html' with prefix='cotis' col='paiement' text=tr_payment_method %}
                </th>
                <th>
                    {% trans "Date" as tr_date %}
                    {% include 'buttons/sort.html' with prefix='cotis' col='date' text=tr_date %}
                </th>
                <th>
                    {% trans "Invoice ID" as tr_invoice_id %}
                    {% include 'buttons/sort.html' with prefix='cotis' col='id' text=tr_invoice_id %}
                </th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        {% for facture in facture_list %}
        <tr>
            <td><a href="{% url 'users:profil' userid=facture.user.id %}">{{ facture.user }}</a></td>
            <td>
                <table class="table-borderless">
                    {% for article in facture.name_detailed %}
                    <tr>
                        <td>
                            {{ article }}
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </td> 
            <td>{{ facture.prix_total }}</td>
            <td>{{ facture.paiement }}</td>
            <td>{{ facture.date }}</td>
            <td>{{ facture.id }}</td>
            <td>
                {% can_edit facture %}
                {% include 'buttons/edit.html' with href='cotisations:edit-facture' id=facture.id %}
                {% acl_else %}
                {% trans "Controlled invoice" %}
                {% acl_end %}
                {% can_delete facture %}
                {% include 'buttons/suppr.html' with href='cotisations:del-facture' id=facture.id %}
                {% acl_end %}
                {% history_button facture %}
            </td>
            <td>
                {% if facture.valid %}
                <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:facture-pdf' facture.id %}">
                    <i class="fa fa-file-pdf-o"></i> {% trans "PDF" %}
                </a>
                {% else %}
                <i class="text-danger">{% trans "Invalidated invoice" %}</i>
                {% endif %}
                {% if facture.control and facture.is_subscription %}
                <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:voucher-pdf' facture.id %}">
                    <i class="fa fa-file-pdf-o"></i> {% trans "Voucher" %}
                </a>
                {% endif %}
            </td>
        </tr>
        {% endfor %}
    </table>

    {% if facture_list.paginator %}
    {% include 'pagination.html' with list=facture_list %}
    {% endif %}
</div>

cotisations/templates/cotisations/aff_profil.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load acl %}
{% load i18n %}
{% load logs_extra %}


<div class="panel panel-default">
    <div class="panel-heading clearfix profil" data-parent="#accordion" data-toggle="collapse"
         data-target="#subscriptions">
        <h3 class="panel-title pull-left">
            <i class="fa fa-eur"></i>
    {% trans "Subscriptions" %}
        </h3>
    </div>
    <div id="subscriptions" class="panel-collapse collapse">
        <div class="panel-body">
            {% can_create Facture %}
            <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:new-facture' users.id %}">
                <i class="fa fa-eur"></i>
        {% trans "Add a subscription" %}
            </a>
            {% if user_solde %}
            <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:credit-solde' users.id %}">
                <i class="fa fa-eur"></i>
        {% trans "Edit the balance" %}
            </a>
            {% endif%}
            {% acl_end %}
        </div>
        <div class="panel-body">
            {% if facture_list %}
                {%  include 'cotisations/aff_cotisations.html' with  facture_list=facture_list %}
            {% else %}
                <p>{% trans "No invoice" %}</p>
            {% endif %}
        </div>
    </div>
</div>

cotisations/templates/cotisations/index.html
{% extends 'cotisations/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans "Invoices" %}{% endblock %}

{% block content %}
    <h2>{% trans "Subscriptions" %}</h2>
    {% include 'cotisations/aff_cotisations.html' with facture_list=facture_list %}
{% endblock %}

cotisations/templates/cotisations/index_article.html
{% extends 'cotisations/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load acl %}
{% load i18n %}

{% block title %}{% trans "Articles" %}{% endblock %}

{% block content %}
    <h2>{% trans "List of articles" %}</h2>
    {% can_create Article %}
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:add-article' %}">
        <i class="fa fa-plus"></i> {% trans "Add an article" %}
    </a>
    {% acl_end %}
    <a class="btn btn-danger btn-sm" role="button" href="{% url 'cotisations:del-article' %}">
        <i class="fa fa-trash"></i> {% trans "Delete one or several articles" %}
    </a>
    {% include 'cotisations/aff_article.html' with  article_list=article_list %}
{% endblock %}

cotisations/templates/cotisations/index_banque.html
{% extends 'cotisations/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load acl %}
{% load i18n %}

{% block title %}{% trans "Banks" %}{% endblock %}

{% block content %}
    <h2>{% trans "List of banks" %}</h2>
    {% can_create Banque %}
    <a class="btn btn-primary btn-sm" role="button" href="{% url 'cotisations:add-banque' %}">
        <i class="fa fa-plus"></i> {% trans "Add a bank" %}
    </a>
    {% acl_end %}
    <a class="btn btn-danger btn-sm" role="button" href="{% url 'cotisations:del-banque' %}">
        <i class="fa fa-trash"></i> {% trans "Delete one or several banks" %}
    </a>
    {% include 'cotisations/aff_banque.html' with  banque_list=banque_list %}
{% endblock %}