api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
# Copyright © 2020 Caroline Canebier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""Defines the URLs of the API

A custom router is used to register all the routes. That allows to register
all the URL patterns from the viewsets as a standard router but, the views
can also be register. That way a complete API root page presenting all URLs
can be generated automatically.
"""

from django.conf.urls import url, include
from importlib import import_module

from . import views
from .routers import AllViewsRouter
from django.conf import settings

router = AllViewsRouter()

urls_viewset = []
urls_view = []
urls_functional_view = []

for app in settings.INSTALLED_APPS:
    try:
        module = import_module(".api.urls", package=app)
        urls_viewset += getattr(module, "urls_viewset", [])
        urls_view += getattr(module, "urls_view", [])
        urls_functional_view += getattr(module, "urls_functional_view", [])
    except ImportError:
        continue

for _url, viewset, name in urls_viewset:
    if name == None:
        router.register_viewset(_url, viewset)
    else:
        router.register_viewset(_url, viewset, basename=name)

for _url, view in urls_view:
    router.register_view(_url, view)

for _url, view, name in urls_functional_view:
    router.register_functional_view(_url, view, name)

# TOKEN AUTHENTICATION
router.register_view(r"token-auth", views.ObtainExpiringAuthToken)

urlpatterns = [url(r"^", include(router.urls))]

re2o/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""re2o URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home)
    3. Optional: Add a custom name for this URL:
         url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view())
    3. Optional: Add a custom name for this URL:
         url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
    2. Optional: Add a custom namespace for all URL using this urlpatterns:
         url(r'^blog/', include('blog.urls'), namespace='blog')
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from .settings_local import OPTIONNAL_APPS_RE2O

from .views import index, about_page, contact_page

# Admin site configuration
admin.site.index_title = _("Homepage")
admin.site.index_template = "admin/custom_index.html"

handler500 = "re2o.views.handler500"
handler404 = "re2o.views.handler404"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^about/$", about_page, name="about"),
    url(r"^contact/$", contact_page, name="contact"),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^search/", include("search.urls", namespace="search")),
    url(r"^cotisations/", include("cotisations.urls", namespace="cotisations")),
    url(r"^machines/", include("machines.urls", namespace="machines")),
    url(r"^topologie/", include("topologie.urls", namespace="topologie")),
    url(r"^logs/", include("logs.urls", namespace="logs")),
    url(r"^preferences/", include("preferences.urls", namespace="preferences")),
    # Include contrib auth and contrib admin
    # manage/login/ is redirected to the non-admin login page
    url(r"^", include("django.contrib.auth.urls")),
    url(r"^admin/login/$", RedirectView.as_view(pattern_name="login")),
    url(r"^admin/", include(admin.site.urls)),
]


urlpatterns += [
    url(r"^{}/".format(app), include("{}.urls".format(app), namespace=app))
    for app in OPTIONNAL_APPS_RE2O
]

# Add debug_toolbar URLs if activated
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]
if "api" in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^api/", include("api.urls", namespace="api"))]

users/api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

from . import views

urls_viewset = [
    (r"users/user", views.UserViewSet, "user"),
    (r"users/homecreation", views.HomeCreationViewSet, "homecreation"),
    (r"users/normaluser", views.NormalUserViewSet, "normaluser"),
    (r"users/criticaluser", views.CriticalUserViewSet, "criticaluser"),
    (r"users/club", views.ClubViewSet, None),
    (r"users/adherent", views.AdherentViewSet, None),
    (r"users/serviceuser", views.ServiceUserViewSet, None),
    (r"users/school", views.SchoolViewSet, None),
    (r"users/listright", views.ListRightViewSet, None),
    (r"users/shell", views.ShellViewSet, "shell"),
    (r"users/ban", views.BanViewSet, None),
    (r"users/whitelist", views.WhitelistViewSet, None),
    (r"users/emailaddress", views.EMailAddressViewSet, None)
]

urls_view = [
    (r"users/localemail", views.LocalEmailUsersView),
    (r"users/mailing-standard", views.StandardMailingView),
    (r"users/mailing-club", views.ClubMailingView),

    # Deprecated
    (r"localemail/users", views.LocalEmailUsersView),
    (r"mailing/standard", views.StandardMailingView),
    (r"mailing/club", views.ClubMailingView),
]

users/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017-2020  Gabriel Détraz
# Copyright © 2017-2020  Lara Kermarec
# Copyright © 2017-2020  Augustin Lemesle
# Copyright © 2017-2020  Hugo Levy--Falk
# Copyright © 2017-2020  Jean-Romain Garnier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
The defined URLs for the Users app
"""

from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from . import views_autocomplete

urlpatterns = [
    url(r"^new_user/$", views.new_user, name="new-user"),
    url(r"^new_club/$", views.new_club, name="new-club"),
    url(r"^edit_info/(?P<userid>[0-9]+)$", views.edit_info, name="edit-info"),
    url(
        r"^edit_club_admin_members/(?P<clubid>[0-9]+)$",
        views.edit_club_admin_members,
        name="edit-club-admin-members",
    ),
    url(r"^state/(?P<userid>[0-9]+)$", views.state, name="state"),
    url(r"^groups/(?P<userid>[0-9]+)$", views.groups, name="groups"),
    url(r"^password/(?P<userid>[0-9]+)$", views.password, name="password"),
    url(r"^confirm_email/(?P<userid>[0-9]+)$", views.resend_confirmation_email, name="resend-confirmation-email"),
    url(
        r"^del_group/(?P<userid>[0-9]+)/(?P<listrightid>[0-9]+)$",
        views.del_group,
        name="del-group",
    ),
    url(
        r"^del_superuser/(?P<userid>[0-9]+)$", views.del_superuser, name="del-superuser"
    ),
    url(r"^new_serviceuser/$", views.new_serviceuser, name="new-serviceuser"),
    url(
        r"^edit_serviceuser/(?P<serviceuserid>[0-9]+)$",
        views.edit_serviceuser,
        name="edit-serviceuser",
    ),
    url(
        r"^del_serviceuser/(?P<serviceuserid>[0-9]+)$",
        views.del_serviceuser,
        name="del-serviceuser",
    ),
    url(r"^add_ban/(?P<userid>[0-9]+)$", views.add_ban, name="add-ban"),
    url(r"^edit_ban/(?P<banid>[0-9]+)$", views.edit_ban, name="edit-ban"),
    url(r"^del-ban/(?P<banid>[0-9]+)$", views.del_ban, name="del-ban"),
    url(
        r"^add_whitelist/(?P<userid>[0-9]+)$", views.add_whitelist, name="add-whitelist"
    ),
    url(
        r"^edit_whitelist/(?P<whitelistid>[0-9]+)$",
        views.edit_whitelist,
        name="edit-whitelist",
    ),
    url(
        r"^del_whitelist/(?P<whitelistid>[0-9]+)$",
        views.del_whitelist,
        name="del-whitelist",
    ),
    url(
        r"^add_emailaddress/(?P<userid>[0-9]+)$",
        views.add_emailaddress,
        name="add-emailaddress",
    ),
    url(
        r"^edit_emailaddress/(?P<emailaddressid>[0-9]+)$",
        views.edit_emailaddress,
        name="edit-emailaddress",
    ),
    url(
        r"^del_emailaddress/(?P<emailaddressid>[0-9]+)$",
        views.del_emailaddress,
        name="del-emailaddress",
    ),
    url(
        r"^edit_email_settings/(?P<userid>[0-9]+)$",
        views.edit_email_settings,
        name="edit-email-settings",
    ),
    url(r"^add_school/$", views.add_school, name="add-school"),
    url(r"^edit_school/(?P<schoolid>[0-9]+)$", views.edit_school, name="edit-school"),
    url(r"^del_school/$", views.del_school, name="del-school"),
    url(r"^add_listright/$", views.add_listright, name="add-listright"),
    url(
        r"^edit_listright/(?P<listrightid>[0-9]+)$",
        views.edit_listright,
        name="edit-listright",
    ),
    url(r"^del_listright/$", views.del_listright, name="del-listright"),
    url(r"^add_shell/$", views.add_shell, name="add-shell"),
    url(r"^edit_shell/(?P<listshellid>[0-9]+)$", views.edit_shell, name="edit-shell"),
    url(r"^del_shell/(?P<listshellid>[0-9]+)$", views.del_shell, name="del-shell"),
    url(r"^profil/(?P<userid>[0-9]+)$", views.profil, name="profil"),
    url(r"^index_ban/$", views.index_ban, name="index-ban"),
    url(r"^index_white/$", views.index_white, name="index-white"),
    url(r"^index_school/$", views.index_school, name="index-school"),
    url(r"^index_shell/$", views.index_shell, name="index-shell"),
    url(r"^index_listright/$", views.index_listright, name="index-listright"),
    url(r"^index_serviceusers/$", views.index_serviceusers, name="index-serviceusers"),
    url(r"^mon_profil/$", views.mon_profil, name="mon-profil"),
    url(r"^process/(?P<token>[a-z0-9]{32})/$", views.process, name="process"),
    url(r"^reset_password/$", views.reset_password, name="reset-password"),
    url(r"^mass_archive/$", views.mass_archive, name="mass-archive"),
    url(r"^$", views.index, name="index"),
    url(r"^index_clubs/$", views.index_clubs, name="index-clubs"),
    url(r"^initial_register/$", views.initial_register, name="initial-register"),
    url(r"^edit_theme/(?P<userid>[0-9]+)$", views.edit_theme, name="edit-theme"),
    ### Autocomplete Views
    url(r'^user-autocomplete/$', views_autocomplete.UserAutocomplete.as_view(), name='user-autocomplete',),
    url(r'^adherent-autocomplete/$', views_autocomplete.AdherentAutocomplete.as_view(), name='adherent-autocomplete',),
    url(r'^club-autocomplete/$', views_autocomplete.ClubAutocomplete.as_view(), name='club-autocomplete',),
    url(r'^school-autocomplete/$', views_autocomplete.SchoolAutocomplete.as_view(), name='school-autocomplete',),
    url(r'^shell-autocomplete/$', views_autocomplete.ShellAutocomplete.as_view(), name='shell-autocomplete',),
]

users/templates/users/aff_listright.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load i18n %}
{% load logs_extra %}

{% if superusers.count %}
<div class="panel panel-default">
    <div class="panel-heading clearfix" data-toggle="collapse" data-target="#collapse_superuser">
        <div class="pull-right">
            <a type="button" class="btn btn-sm btn-default" data-toggle="modal" data-target="#modal_superuser">
                {{ superusers.count }} <i class="fa fa-user"></i>
            </a>
        </div>
        <h4 class="text-danger">
            <i class="fa fa-address-book"></i>
            {% trans "Superuser" %}
        </h4>
        {% trans "Django's specific pre-defined right that supersedes any other rights." %}
    </div>
    <div class="panel-collapse collapse" id="collapse_superuser">
        <div class="panel-body">
            <h4 class="text-danger">{% trans "Total: all permissions" %}</h4>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_superuser" tabindex="-1" role="dialog" aria-labelledby={% trans "Users in Superuser" %}>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label={% trans "Close" %}>
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title" id="myModalLabel">{% trans "Users in Superuser" %}</h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>{% trans "Username" %}</th>
                                <th>{% trans "Membership" %}</th>
                                <th>{% trans "Last seen" %}</th>
                                <th>{% trans "Actions" %}</th>
                                <th>{% trans "Last action" %}</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for user in superusers %}
                        <tr>
                            <td>{{ user.pseudo }}</td>
                            {% if user.end_adhesion is not None and user.end_adhesion >= now_aware %}
                            <td class="text-success">{% trans "Member" %}</td>
                            {% elif not user.end_adhesion %}
                            <td class="text-warning">{% trans "No membership records" %}</td>
                            {% else %}
                            <td class="text-danger">
                                {% blocktrans trimmed with user.end_adhesion as end_date %}
                                Not since {{ end_date }}
                                {% endblocktrans %}
                            </td>
                            {% endif %}
                            <td>{{ user.last_login }}</td>
                            <td>{{ user.action_number }}</td>
                            {% if not user.last_seen %}
                            <td class="text-danger">{% trans "Never" %}</td>
                            {% else %}
                            <td class="text-success">{{ user.last_seen }}</td>
                            {% endif %}
                            <td>
                                <a class="btn btn-danger" role="button" href="{% url 'users:del-superuser' user.id %}">
                                    <span class="fa fa-user-times" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}

{% for right, users in rights.items %}
<div class="panel panel-default">
    <div class="panel-heading clearfix" data-toggle="collapse" data-target="#collapse_{{right.id}}">
        <div class="pull-right">
            {% if users %}
            <a type="button" class="btn btn-sm btn-default" data-toggle="modal" data-target="#modal_{{right.id}}">
                {% else %}
                <a type="button" class="btn btn-sm btn-default" disabled="disabled">
                    {% endif %}
                    {{users.count}} <i class="fa fa-user"></i>
                </a>
                {% include 'buttons/edit.html' with href='users:edit-listright' id=right.id %}
                {% history_button right %}
        </div>
        <h4 class="{% if right.critical %}text-danger{% endif %}">
            <i class="fa fa-address-book"></i>
            {% blocktrans trimmed with right.name as right_name and right.gid as right_gid %}
            {{ right_name }} (gid: {{ right_gid }})
            {% endblocktrans %}
        </h4>
        {{ right.details }}
    </div>
    <div class="panel-collapse collapse" id="collapse_{{right.id}}">
        <div class="panel-body">
            <h4>
                {% blocktrans trimmed count right.permissions.count as perm_count%}
                Total: {{ perm_count }} permission
                {% plural %}
                Total: {{ perm_count }} permissions
                {% endblocktrans %}
            </h4>
            <ul class="list-group" style="margin-bottom: 0px">
                {% for perm in right.permissions.all %}
                <li class="list-group-item col-xs-6 col-sm-4 col-md-3" style="border:none;">
                    {{perm.name}}
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% if users %}
<div class="modal fade" id="modal_{{right.id}}" tabindex="-1" role="dialog" aria-labelledby={% trans "Users" %}>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label={% trans "Close" %}>
                    <i class="fa fa-times"></i>
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    {% blocktrans trimmed with right.name as right_name %}
                    Users in {{ right_name }}
                    {% endblocktrans %}
                </h4>
            </div>
            <div class="modal-body">
                <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                            <tr>
                                <th>{% trans "Username" %}</th>
                                <th>{% trans "Membership" %}</th>
                                <th>{% trans "Last seen" %}</th>
                                <th>{% trans "Actions" %}</th>
                                <th>{% trans "Last action" %}</th>
                                <th></th>
                            </tr>
                        </thead>
                        {% for user in users %}
                        <tr>
                            <td>{{ user.pseudo }}</td>
                            {% if user.end_adhesion is not None and user.end_adhesion >= now_aware %}
                            <td class="text-success">{% trans "Member" %}</td>
                            {% elif not user.end_adhesion %}
                            <td class="text-warning">{% trans "No membership records" %}</td>
                            {% else %}
                            <td class="text-danger">
                                {% blocktrans trimmed with user.end_adhesion as end_date %}
                                Not since {{ end_date }}
                                {% endblocktrans %}
                            </td>
                            {% endif %}
                            <td>{{ user.last_login }}</td>
                            <td>{{ user.action_number }}</td>
                            {% if not user.last_seen %}
                            <td class="text-danger">{% trans "Never" %}</td>
                            {% else %}
                            <td class="text-success">{{ user.last_seen }}</td>
                            {% endif %}
                            <td>
                                <a class="btn btn-danger" role="button" href="{% url 'users:del-group' user.id right.id %}">
                                    <span class="fa fa-user-times" aria-hidden="true"></span>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endfor %}

users/templates/users/index_clubs.html
{% extends 'users/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load i18n %}
{% load acl %}

{% block title %}{% trans "Users" %}{% endblock %}

{% block content %}
<h2>{% trans "Clubs" %}</h2>
  {% can_create Club %}
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:new-club'  %}"><i class="fa fa-plus"></i> {% trans "Add a club" %}</a>
  {% acl_end %}
  {%  include 'users/aff_clubs.html' with  clubs_list=clubs_list %}
  <br />
  <br />
  <br />
{% endblock %}

users/templates/users/index_listright.html
{% extends 'users/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load acl %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock %}

{% block content %}
<h2>{% trans "List of groups of rights" %}</h2>
  {% can_create ListRight %}
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:add-listright'  %}"><i class="fa fa-plus"></i> {% trans "Add a group of rights" %}</a>
  {% acl_end %}
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'users:del-listright'  %}"><i class="fa fa-trash"></i> {% trans "Delete one or several groups of rights" %}</a>
  <br />
  <br />
  {%  include 'users/aff_listright.html' %}
{% endblock %}

users/templates/users/index_schools.html
{% extends 'users/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load acl %}
{% load i18n %}

{% block title %}{% trans "Users" %}{% endblock %}

{% block content %}
  <h2>{% trans "List of schools" %}</h2>
  <h5>{% trans "List of schools for registered users" %}</h5>
  {% can_create School %}
  <a class="btn btn-primary btn-sm" role="button" href="{% url 'users:add-school'  %}"><i class="fa fa-plus"></i> {% trans "Add a school" %}</a>
  {% acl_end %}
  <a class="btn btn-danger btn-sm" role="button" href="{% url 'users:del-school'  %}"><i class="fa fa-trash"></i> {% trans "Delete one or several schools" %}</a>
  <hr>
  {%  include 'users/aff_schools.html' with  school_list=school_list %}
  <br />
  <br />
  <br />
{% endblock %}