api/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2018 Maël Kervella
# Copyright © 2020 Caroline Canebier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""Defines the URLs of the API

A custom router is used to register all the routes. That allows to register
all the URL patterns from the viewsets as a standard router but, the views
can also be register. That way a complete API root page presenting all URLs
can be generated automatically.
"""

from django.conf.urls import url, include
from importlib import import_module

from . import views
from .routers import AllViewsRouter
from django.conf import settings

router = AllViewsRouter()

urls_viewset = []
urls_view = []
urls_functional_view = []

for app in settings.INSTALLED_APPS:
    try:
        module = import_module(".api.urls", package=app)
        urls_viewset += getattr(module, "urls_viewset", [])
        urls_view += getattr(module, "urls_view", [])
        urls_functional_view += getattr(module, "urls_functional_view", [])
    except ImportError:
        continue

for _url, viewset, name in urls_viewset:
    if name == None:
        router.register_viewset(_url, viewset)
    else:
        router.register_viewset(_url, viewset, basename=name)

for _url, view in urls_view:
    router.register_view(_url, view)

for _url, view, name in urls_functional_view:
    router.register_functional_view(_url, view, name)

# TOKEN AUTHENTICATION
router.register_view(r"token-auth", views.ObtainExpiringAuthToken)

urlpatterns = [url(r"^", include(router.urls))]

logs/urls.py
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""logs.urls
The defined URLs for the logs app. Included in re2o.urls.
"""
from __future__ import unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"^$", views.index, name="index"),
    url(r"^stats_logs$", views.stats_logs, name="stats-logs"),
    url(
        r"^revert_action/(?P<revision_id>[0-9]+)$",
        views.revert_action,
        name="revert-action",
    ),
    url(
        r"(?P<application>\w+)/(?P<object_name>\w+)/(?P<object_id>[0-9]+)$",
        views.history,
        name="history",
    ),
    url(r"^stats_general/$", views.stats_general, name="stats-general"),
    url(r"^stats_models/$", views.stats_models, name="stats-models"),
    url(r"^stats_users/$", views.stats_users, name="stats-users"),
    url(r"^stats_actions/$", views.stats_actions, name="stats-actions"),
    url(r"^stats_search_machine/$", views.stats_search_machine_history, name="stats-search-machine"),
]

re2o/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017  Gabriel Détraz
# Copyright © 2017  Lara Kermarec
# Copyright © 2017  Augustin Lemesle
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

"""re2o URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home)
    3. Optional: Add a custom name for this URL:
         url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view())
    3. Optional: Add a custom name for this URL:
         url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
    2. Optional: Add a custom namespace for all URL using this urlpatterns:
         url(r'^blog/', include('blog.urls'), namespace='blog')
"""
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.utils.translation import ugettext_lazy as _
from django.views.generic import RedirectView

from .settings_local import OPTIONNAL_APPS_RE2O

from .views import index, about_page, contact_page

# Admin site configuration
admin.site.index_title = _("Homepage")
admin.site.index_template = "admin/custom_index.html"

handler500 = "re2o.views.handler500"
handler404 = "re2o.views.handler404"

urlpatterns = [
    url(r"^$", index, name="index"),
    url(r"^about/$", about_page, name="about"),
    url(r"^contact/$", contact_page, name="contact"),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(r"^users/", include("users.urls", namespace="users")),
    url(r"^search/", include("search.urls", namespace="search")),
    url(r"^cotisations/", include("cotisations.urls", namespace="cotisations")),
    url(r"^machines/", include("machines.urls", namespace="machines")),
    url(r"^topologie/", include("topologie.urls", namespace="topologie")),
    url(r"^logs/", include("logs.urls", namespace="logs")),
    url(r"^preferences/", include("preferences.urls", namespace="preferences")),
    # Include contrib auth and contrib admin
    # manage/login/ is redirected to the non-admin login page
    url(r"^", include("django.contrib.auth.urls")),
    url(r"^admin/login/$", RedirectView.as_view(pattern_name="login")),
    url(r"^admin/", include(admin.site.urls)),
]


urlpatterns += [
    url(r"^{}/".format(app), include("{}.urls".format(app), namespace=app))
    for app in OPTIONNAL_APPS_RE2O
]

# Add debug_toolbar URLs if activated
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [url(r"^__debug__/", include(debug_toolbar.urls))]
if "api" in settings.INSTALLED_APPS:
    urlpatterns += [url(r"^api/", include("api.urls", namespace="api"))]

users/urls.py
# -*- mode: python; coding: utf-8 -*-
# Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
# se veut agnostique au réseau considéré, de manière à être installable en
# quelques clics.
#
# Copyright © 2017-2020  Gabriel Détraz
# Copyright © 2017-2020  Lara Kermarec
# Copyright © 2017-2020  Augustin Lemesle
# Copyright © 2017-2020  Hugo Levy--Falk
# Copyright © 2017-2020  Jean-Romain Garnier
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
"""
The defined URLs for the Users app
"""

from __future__ import unicode_literals

from django.conf.urls import url

from . import views
from . import views_autocomplete

urlpatterns = [
    url(r"^new_user/$", views.new_user, name="new-user"),
    url(r"^new_club/$", views.new_club, name="new-club"),
    url(r"^edit_info/(?P<userid>[0-9]+)$", views.edit_info, name="edit-info"),
    url(
        r"^edit_club_admin_members/(?P<clubid>[0-9]+)$",
        views.edit_club_admin_members,
        name="edit-club-admin-members",
    ),
    url(r"^state/(?P<userid>[0-9]+)$", views.state, name="state"),
    url(r"^groups/(?P<userid>[0-9]+)$", views.groups, name="groups"),
    url(r"^password/(?P<userid>[0-9]+)$", views.password, name="password"),
    url(r"^confirm_email/(?P<userid>[0-9]+)$", views.resend_confirmation_email, name="resend-confirmation-email"),
    url(
        r"^del_group/(?P<userid>[0-9]+)/(?P<listrightid>[0-9]+)$",
        views.del_group,
        name="del-group",
    ),
    url(
        r"^del_superuser/(?P<userid>[0-9]+)$", views.del_superuser, name="del-superuser"
    ),
    url(r"^new_serviceuser/$", views.new_serviceuser, name="new-serviceuser"),
    url(
        r"^edit_serviceuser/(?P<serviceuserid>[0-9]+)$",
        views.edit_serviceuser,
        name="edit-serviceuser",
    ),
    url(
        r"^del_serviceuser/(?P<serviceuserid>[0-9]+)$",
        views.del_serviceuser,
        name="del-serviceuser",
    ),
    url(r"^add_ban/(?P<userid>[0-9]+)$", views.add_ban, name="add-ban"),
    url(r"^edit_ban/(?P<banid>[0-9]+)$", views.edit_ban, name="edit-ban"),
    url(r"^del-ban/(?P<banid>[0-9]+)$", views.del_ban, name="del-ban"),
    url(
        r"^add_whitelist/(?P<userid>[0-9]+)$", views.add_whitelist, name="add-whitelist"
    ),
    url(
        r"^edit_whitelist/(?P<whitelistid>[0-9]+)$",
        views.edit_whitelist,
        name="edit-whitelist",
    ),
    url(
        r"^del_whitelist/(?P<whitelistid>[0-9]+)$",
        views.del_whitelist,
        name="del-whitelist",
    ),
    url(
        r"^add_emailaddress/(?P<userid>[0-9]+)$",
        views.add_emailaddress,
        name="add-emailaddress",
    ),
    url(
        r"^edit_emailaddress/(?P<emailaddressid>[0-9]+)$",
        views.edit_emailaddress,
        name="edit-emailaddress",
    ),
    url(
        r"^del_emailaddress/(?P<emailaddressid>[0-9]+)$",
        views.del_emailaddress,
        name="del-emailaddress",
    ),
    url(
        r"^edit_email_settings/(?P<userid>[0-9]+)$",
        views.edit_email_settings,
        name="edit-email-settings",
    ),
    url(r"^add_school/$", views.add_school, name="add-school"),
    url(r"^edit_school/(?P<schoolid>[0-9]+)$", views.edit_school, name="edit-school"),
    url(r"^del_school/$", views.del_school, name="del-school"),
    url(r"^add_listright/$", views.add_listright, name="add-listright"),
    url(
        r"^edit_listright/(?P<listrightid>[0-9]+)$",
        views.edit_listright,
        name="edit-listright",
    ),
    url(r"^del_listright/$", views.del_listright, name="del-listright"),
    url(r"^add_shell/$", views.add_shell, name="add-shell"),
    url(r"^edit_shell/(?P<listshellid>[0-9]+)$", views.edit_shell, name="edit-shell"),
    url(r"^del_shell/(?P<listshellid>[0-9]+)$", views.del_shell, name="del-shell"),
    url(r"^profil/(?P<userid>[0-9]+)$", views.profil, name="profil"),
    url(r"^index_ban/$", views.index_ban, name="index-ban"),
    url(r"^index_white/$", views.index_white, name="index-white"),
    url(r"^index_school/$", views.index_school, name="index-school"),
    url(r"^index_shell/$", views.index_shell, name="index-shell"),
    url(r"^index_listright/$", views.index_listright, name="index-listright"),
    url(r"^index_serviceusers/$", views.index_serviceusers, name="index-serviceusers"),
    url(r"^mon_profil/$", views.mon_profil, name="mon-profil"),
    url(r"^process/(?P<token>[a-z0-9]{32})/$", views.process, name="process"),
    url(r"^reset_password/$", views.reset_password, name="reset-password"),
    url(r"^mass_archive/$", views.mass_archive, name="mass-archive"),
    url(r"^$", views.index, name="index"),
    url(r"^index_clubs/$", views.index_clubs, name="index-clubs"),
    url(r"^initial_register/$", views.initial_register, name="initial-register"),
    url(r"^edit_theme/(?P<userid>[0-9]+)$", views.edit_theme, name="edit-theme"),
    ### Autocomplete Views
    url(r'^user-autocomplete/$', views_autocomplete.UserAutocomplete.as_view(), name='user-autocomplete',),
    url(r'^adherent-autocomplete/$', views_autocomplete.AdherentAutocomplete.as_view(), name='adherent-autocomplete',),
    url(r'^club-autocomplete/$', views_autocomplete.ClubAutocomplete.as_view(), name='club-autocomplete',),
    url(r'^school-autocomplete/$', views_autocomplete.SchoolAutocomplete.as_view(), name='school-autocomplete',),
    url(r'^shell-autocomplete/$', views_autocomplete.ShellAutocomplete.as_view(), name='shell-autocomplete',),
]

logs/templates/logs/aff_stats_general.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% for stats in stats_list %}
    <table class="table table-striped">
        <thead>
            <tr>
                {% for element in stats.0 %}
                <th>{{ element }}</th>
                {% endfor %}
            </tr>
        </thead>
       {% for key, stat in stats.1.items %}
           <tr>
               {% for item in stat %}
               <td>{{ item }}</td>
               {% endfor %}
           </tr>
       {% endfor %}
    </table>
{% endfor %}

logs/templates/logs/aff_stats_logs.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% if revisions_list.paginator %}
    {% include 'pagination.html' with list=revisions_list %}
{% endif %}

{% load logs_extra %}
{% load acl %}
{% load i18n %}

<table class="table table-striped">
    <thead>
        <tr>
            <th>{% trans "Edited object" %}</th>
            {% trans "Edited by" as tr_edited_by %}
            <th>{% include 'buttons/sort.html' with prefix='logs' col='author' text=tr_edited_by %}</th>
            {% trans "Date of editing" as tr_date_of_editing %}
            <th>{% include 'buttons/sort.html' with prefix='logs' col='date' text=tr_date_of_editing %}</th>
            <th>{% trans "Edited" %}</th>
            <th>{% trans "Comment" %}</th>
            <th></th>
        </tr>
    </thead>
    {% for revision in revisions_list %}
        {% for version in revision.versions %}
            <tr>
                <td>
                    {% if version.object_id %}
                    <a href="{% url 'logs:history' version.application version.model_name version.object_id %}" title="{% trans "History" %}">
                        {{ version.name }}
                    </a>
                    {% else %}
                        {{ version.name }}
                    {% endif %}
                </td>
                <td>
                    {% if revision.performed_by %}
                    <a href="{% url 'users:profil' userid=revision.performed_by.id %}" title=tr_view_the_profile>
                        {{ revision.performed_by }}
                    </a>
                    {% else %}
                        {{ revision.performed_by }}
                    {% endif %}
                </td>
                <td>{{ revision.date_created }}</td>
                <td>
                    {% for edit in version.edits %}
                        {% if edit.1 is None and edit.2 is None %}
                            <strong>{{ edit.0 }}</strong><br/>
                        {% elif edit.1 is None %}
                            <strong>{{ edit.0 }}:</strong>
                            <i class="text-success"> {{ edit.2|truncatechars:50 }}</i><br/>
                        {% else %}
                            <strong>{{ edit.0 }}:</strong>
                            <i class="text-danger"> {{ edit.1|truncatechars:50 }} </i>
                            ➔ <i class="text-success">{{ edit.2|truncatechars:50 }}</i><br/>
                        {% endif %}
                    {% endfor %}
                </td>
                <td>{{ revision.comment }}</td>
                {% can_edit_history %}
                <td>
                    <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' revision.id %}">
                        <i class="fa fa-times"></i>
                        {% trans "Cancel" %}
                    </a>
                </td>
                {% acl_end %}
            </tr>
        {% endfor %}
    {% endfor %}
</table>

{% if revisions_list.paginator %}
    {% include 'pagination.html' with list=revisions_list %}
{% endif %}

logs/templates/logs/aff_summary.html
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2017  Gabriel Détraz
Copyright © 2017  Lara Kermarec
Copyright © 2017  Augustin Lemesle

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% if versions_list.paginator %}
    {% include 'pagination.html' with list=versions_list %}
{% endif %}

{% load logs_extra %}
{% load acl %}

{% load i18n %}

<table class="table table-striped">
    <thead>
        <tr>
            {% trans "Date" as tr_date %}
            <th>{% include 'buttons/sort.html' with prefix='sum' col='date' text=tr_date %}</th>
            <th>{% trans "Editing" %}</th>
            <th></th>
        </tr>
    </thead>
    {% for v in versions_list %}
    {% if v.version.content_type.model == 'ban' %}
        <tr class="danger">
            <td>{{ v.datetime|date:"j/m/y H:i:s" }}</td>
            <td>
                {% blocktrans with username=v.username %}{{ username }} has banned{% endblocktrans %}
                <a href="{% url 'users:profil' v.version.object.user_id %}">{{ v.version.object.user.get_username }}</a>
                (<i>
                {% if v.version.object.raison == '' %}
                    {% trans "No reason" %}
                {% else %}
                    {{ v.version.object.raison }}
                {% endif %}
                </i>)
            </td>
	    {% can_edit_history %}
            <td>
                <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' v.rev_id %}">
                    <i class="fa fa-times"></i>
                    {% trans "Cancel" %}
                </a>
            </td>
            {% acl_end %}
        </tr>
    {% elif v.version.content_type.model == 'whitelist' %}
        <tr class="success">
            <td>{{ v.datetime|date:"j/m/y H:i:s" }}</td>
            <td>
                {% blocktrans with username=v.username %}{{ username }} has graciously authorised{% endblocktrans %}
                <a href="{% url 'users:profil' v.version.object.user_id %}">{{ v.version.object.user.get_username }}</a>
                (<i>
                {% if v.version.object.raison == '' %}
                    {% trans "No reason" %}
                {% else %}
                    {{ v.version.object.raison }}
                {% endif %}
                </i>)
            </td>
            {% can_edit_history%}
            <td>
                <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' v.rev_id %}">
                    <i class="fa fa-times"></i>
                    {% trans "Cancel" %}
                </a>
            </td>
            {% acl_end %}
        </tr>
    {% elif v.version.content_type.model == 'user' %}
        <tr>
            <td>{{ v.datetime|date:"j/m/y H:i:s" }}</td>
            <td>
                {% blocktrans with username=v.username %}{{ username }} has updated{% endblocktrans %}
                <a href="{% url 'users:profil' v.version.object.id %}">{{ v.version.object.get_username }}</a>
                {% if v.comment != '' %}
                    (<i>{{ v.comment }}</i>)
                {% endif %}
            </td>
            {% can_edit_history %}
            <td>
                <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' v.rev_id %}">
                    <i class="fa fa-times"></i>
                    {% trans "Cancel" %}
                </a>
            </td>
            {% acl_end %}
        </tr>
    {% elif v.version.content_type.model == 'vente' %}
        <tr>
            <td>{{ v.datetime|date:"j/m/y H:i:s" }}</td>
            <td>
                {% blocktrans with username=v.username number=v.version.object.number name=v.version.object.name %}{{ username }} has sold {{ number }}x {{ name }}{% endblocktrans %}
                {% with invoice=v.version.object.facture %}
                {% if invoice|is_facture %}
                {% trans "to" %}
                <a href="{% url 'users:profil' v.version.object.facture.facture.user_id %}">{{ v.version.object.facture.facture.user.get_username }}</a>
                {% if v.version.object.iscotisation %}
                    (<i>{% blocktrans with duration=v.version.object.duration %}+{{ duration }} months{% endblocktrans %}</i>)
                {% endif %}
                {% endif %}
                {% endwith %}
            </td>
            {% can_edit_history %}
            <td>
                <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' v.rev_id %}">
                    <i class="fa fa-times"></i>
                    {% trans "Cancel" %}
                </a>
            </td>
            {% acl_end %}
        </tr>
    {% elif v.version.content_type.model == 'interface' %}
        <tr>
            <td>{{ v.datetime|date:"j/m/y H:i:s" }}</td>
            <td>
                {% blocktrans with username=v.username %}{{ username }} has edited an interface of{% endblocktrans %}
                <a href="{% url 'users:profil' v.version.object.machine.user_id %}">{{ v.version.object.machine.user.get_username }}</a>
                {% if v.comment != '' %}
                    (<i>{{ v.comment }}</i>)
                {% endif %}
            </td>
            {% can_edit_history %}
            <td>
                <a class="btn btn-danger btn-sm" role="button" href="{% url 'logs:revert-action' v.rev_id %}">
                    <i class="fa fa-times"></i>
                    {% trans "Cancel" %}
                </a>
            </td>
            {% acl_end %}
        </tr>
    {% endif %}
    {% endfor %}
</table>

{% if versions_list.paginator %}
    {% include 'pagination.html' with list=versions_list %}
{% endif %}

logs/templates/logs/machine_history.html
{% extends 'logs/sidebar.html' %}
{% comment %}
Re2o est un logiciel d'administration développé initiallement au Rézo Metz. Il
se veut agnostique au réseau considéré, de manière à être installable en
quelques clics.

Copyright © 2020  Jean-Romain Garnier

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
{% endcomment %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans "Search results" %}{% endblock %}

{% block content %}
    {% if events %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>{% trans "User" %}</th>
                    <th>{% trans "IPv4" %}</th>
                    <th>{% trans "MAC address" %}</th>
                    <th>{% trans "Start date" %}</th>
                    <th>{% trans "End date" %}</th>
                    <th>{% trans "Comment" %}</th>
                </tr>
            </thead>
            {% for event in events %}
            <tr>
                <td>
                    <a href="{% url 'users:profil' userid=event.user.id %}" title=tr_view_the_profile>
                        {{ event.user }}
                    </a>
                </td>
                <td>{{ event.ipv4 }}</td>
                <td>{{ event.mac }}</td>
                <td>
                    {% if event.start_date %}
                        {{ event.start_date }}
                    {% else %}
                        {% trans "Unknown" %}
                    {% endif %}
                </td>
                <td>
                    {% if event.end_date %}
                        {{ event.end_date }}
                    {% else %}
                        {% trans "Now" %}
                    {% endif %}
                </td>
                <td>{{ event.comment }}</td>
            </tr>
            {% endfor %}
        </table>
        {% include 'pagination.html' with list=events %}
    {% else %}
        <h3>{% trans "No result" %}</h3>
    {% endif %}
    <br />
    <br />
    <br />
{% endblock %}